# SPDX-License-Identifier: Apache-2.0
"""Tests for :mod:`scripts.p1_prepare_aozora`."""
from __future__ import annotations

import io
import json
import os
import re
import subprocess
import sys
import zipfile
from email.message import Message
from importlib import import_module
from pathlib import Path

import pytest

p1_prepare_aozora = import_module("scripts.p1_prepare_aozora")

AOZORA_SAMPLE = (
    "吾輩は猫である\n"
    "夏目漱石\n"
    "\n"
    "-------------------------------------------------------\n"
    "【テキスト中に現れる記号について】\n"
    "《》：ルビ\n"
    "-------------------------------------------------------\n"
    "吾輩《わがはい》は猫である。｜名前《なまえ》はまだ無い。\n"
    "　どこで生れたか［＃「生れた」に傍点］見当がつかぬ。\n"
    "\n"
    "底本：「吾輩は猫である」岩波書店\n"
    "入力：青空文庫\n"
)


def _aozora_zip_bytes(text: str = AOZORA_SAMPLE) -> bytes:
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w") as zf:
        zf.writestr("sample.txt", text.encode("cp932"))
    return buf.getvalue()


class _FakeResponse:
    def __init__(self, payload: bytes) -> None:
        self._payload = payload

    def read(self) -> bytes:
        return self._payload

    def __enter__(self) -> _FakeResponse:
        return self

    def __exit__(self, exc_type: object, exc: object, tb: object) -> None:
        return None


class _StaticOpener:
    def __init__(self, payload: bytes) -> None:
        self._payload = payload

    def open(self, url: str, timeout: float = 30.0) -> _FakeResponse:
        return _FakeResponse(self._payload)


def test_default_output_name_uses_card_id_and_zip_stem() -> None:
    name = p1_prepare_aozora._default_output_name(  # pyright: ignore[reportPrivateUsage]
        "https://www.aozora.gr.jp/cards/000148/files/789_ruby_5639.zip"
    )
    assert name == "aozora_000148_789_ruby_5639.txt"


def test_prepare_aozora_corpora_writes_cleaned_utf8_files(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    payload = _aozora_zip_bytes()
    monkeypatch.setattr(
        p1_prepare_aozora.urllib.request,
        "build_opener",
        lambda *handlers: _StaticOpener(payload),
    )
    records = p1_prepare_aozora.prepare_aozora_corpora(
        ["https://www.aozora.gr.jp/cards/000148/files/789_ruby_5639.zip"],
        out_dir=tmp_path,
    )
    assert len(records) == 1
    output_path = Path(records[0]["path"])
    assert output_path.exists()
    text = output_path.read_text(encoding="utf-8")
    assert "名前はまだ無い。" in text
    assert "《" not in text
    assert records[0]["chars"] == len(text)
    metadata = json.loads((tmp_path / "aozora_000148_789_ruby_5639.txt.source.json").read_text(encoding="utf-8"))
    assert metadata["url"].endswith("789_ruby_5639.zip")
    assert metadata["reused_existing"] is False


def test_main_supports_url_manifest_and_writes_relative_manifest(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    payload = _aozora_zip_bytes()
    monkeypatch.setattr(
        p1_prepare_aozora.urllib.request,
        "build_opener",
        lambda *handlers: _StaticOpener(payload),
    )
    out_dir = tmp_path / "prepared"
    url_manifest = tmp_path / "urls.txt"
    corpus_manifest = tmp_path / "nested" / "corpora.txt"
    report_json = tmp_path / "nested" / "reports" / "report.json"
    url_manifest.write_text(
        "# comment\nhttps://www.aozora.gr.jp/cards/000148/files/789_ruby_5639.zip\n",
        encoding="utf-8",
    )
    rc = p1_prepare_aozora.main(
        [
            "--out-dir",
            str(out_dir),
            "--url-manifest",
            str(url_manifest),
            "--write-manifest",
            str(corpus_manifest),
            "--json",
            str(report_json),
        ]
    )
    assert rc == 0
    assert corpus_manifest.read_text(encoding="utf-8") == (
        "# Generated by scripts/p1_prepare_aozora.py\n"
        "../prepared/aozora_000148_789_ruby_5639.txt\n"
    )
    payload_json = json.loads(report_json.read_text(encoding="utf-8"))
    bundle_payload = json.loads(
        corpus_manifest.with_suffix(".txt.bundle.json").read_text(encoding="utf-8")
    )
    assert bundle_payload["generated_by"] == "scripts/p1_prepare_aozora.py"
    assert bundle_payload["bundle"]["files"][0]["sha256"] == payload_json["records"][0]["sha256"]
    assert bundle_payload["bundle"]["combined"]["includes_base"] is False
    assert payload_json["records"][0]["url"].endswith("789_ruby_5639.zip")


def test_main_rejects_empty_url_input_via_argparse(capsys: pytest.CaptureFixture[str]) -> None:
    with pytest.raises(SystemExit) as excinfo:
        p1_prepare_aozora.main(["--out-dir", "out"])
    assert excinfo.value.code == 2
    captured = capsys.readouterr()
    assert "expected at least one Aozora zip URL" in captured.err


def test_prepare_aozora_corpora_rejects_output_name_collisions(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    payload = _aozora_zip_bytes()
    monkeypatch.setattr(
        p1_prepare_aozora.urllib.request,
        "build_opener",
        lambda *handlers: _StaticOpener(payload),
    )
    with pytest.raises(ValueError, match="collision"):
        p1_prepare_aozora.prepare_aozora_corpora(
            [
                "https://www.aozora.gr.jp/files/shared.zip",
                "https://aozora.gr.jp/files/shared.zip",
            ],
            out_dir=tmp_path,
        )


def test_prepare_aozora_corpora_rejects_existing_output_before_download(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    existing = tmp_path / "aozora_000148_789_ruby_5639.txt"
    existing.write_text("old\n", encoding="utf-8")
    called = False

    class _UnexpectedOpener:
        def open(self, url: str, timeout: float = 30.0) -> _FakeResponse:
            nonlocal called
            called = True
            return _FakeResponse(_aozora_zip_bytes())

    monkeypatch.setattr(
        p1_prepare_aozora.urllib.request,
        "build_opener",
        lambda *handlers: _UnexpectedOpener(),
    )
    with pytest.raises(ValueError, match="without provenance metadata"):
        p1_prepare_aozora.prepare_aozora_corpora(
            ["https://www.aozora.gr.jp/cards/000148/files/789_ruby_5639.zip"],
            out_dir=tmp_path,
        )
    assert existing.read_text(encoding="utf-8") == "old\n"
    assert called is False


def test_prepare_aozora_corpora_detects_collision_before_any_write(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    called = False

    class _UnexpectedOpener:
        def open(self, url: str, timeout: float = 30.0) -> _FakeResponse:
            nonlocal called
            called = True
            return _FakeResponse(_aozora_zip_bytes())

    monkeypatch.setattr(
        p1_prepare_aozora.urllib.request,
        "build_opener",
        lambda *handlers: _UnexpectedOpener(),
    )
    with pytest.raises(ValueError, match="output filename collision"):
        p1_prepare_aozora.prepare_aozora_corpora(
            [
                "https://www.aozora.gr.jp/files/shared.zip",
                "https://aozora.gr.jp/files/shared.zip",
            ],
            out_dir=tmp_path,
        )
    assert not list(tmp_path.glob("*.txt"))
    assert called is False


def test_prepare_aozora_corpora_is_batch_atomic_on_late_download_failure(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    good_payload = _aozora_zip_bytes("甲\n\n-------------------------------------------------------\n【記号】\n-------------------------------------------------------\n本文\n")
    bad_payload = b"not-a-zip"

    class _MixedOpener:
        def open(self, url: str, timeout: float = 30.0) -> _FakeResponse:
            if "000148" in url:
                return _FakeResponse(good_payload)
            return _FakeResponse(bad_payload)

    monkeypatch.setattr(
        p1_prepare_aozora.urllib.request,
        "build_opener",
        lambda *handlers: _MixedOpener(),
    )
    with pytest.raises(ValueError, match="failed to fetch or decode Aozora zip"):
        p1_prepare_aozora.prepare_aozora_corpora(
            [
                "https://www.aozora.gr.jp/cards/000148/files/789_ruby_5639.zip",
                "https://www.aozora.gr.jp/cards/000149/files/other_1.zip",
            ],
            out_dir=tmp_path,
        )
    assert not list(tmp_path.glob("*.txt"))
    assert not list(tmp_path.glob("*.source.json"))


def test_prepare_aozora_corpora_is_batch_atomic_on_second_corpus_commit_failure(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    payload = _aozora_zip_bytes()

    class _StaticBatchOpener:
        def open(self, url: str, timeout: float = 30.0) -> _FakeResponse:
            return _FakeResponse(payload)

    real_replace = os.replace
    corpus_replace_count = 0

    def _failing_replace(src: os.PathLike[str] | str, dst: os.PathLike[str] | str) -> None:
        nonlocal corpus_replace_count
        dst_path = Path(dst)
        if dst_path.name.endswith(".txt") and not dst_path.name.endswith(".source.json"):
            corpus_replace_count += 1
            if corpus_replace_count == 2:
                raise OSError("boom on second corpus commit")
        real_replace(src, dst)

    monkeypatch.setattr(
        p1_prepare_aozora.urllib.request,
        "build_opener",
        lambda *handlers: _StaticBatchOpener(),
    )
    monkeypatch.setattr(p1_prepare_aozora.os, "replace", _failing_replace)
    with pytest.raises(OSError, match="second corpus commit"):
        p1_prepare_aozora.prepare_aozora_corpora(
            [
                "https://www.aozora.gr.jp/cards/000148/files/789_ruby_5639.zip",
                "https://www.aozora.gr.jp/cards/000149/files/other_1.zip",
            ],
            out_dir=tmp_path,
        )
    assert not list(tmp_path.glob("*.txt"))
    assert not list(tmp_path.glob("*.source.json"))
    assert not list(tmp_path.glob("*.tmp"))


def test_prepare_aozora_corpora_is_batch_atomic_on_sidecar_commit_failure(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    payload = _aozora_zip_bytes()

    class _StaticBatchOpener:
        def open(self, url: str, timeout: float = 30.0) -> _FakeResponse:
            return _FakeResponse(payload)

    real_replace = os.replace

    def _failing_replace(src: os.PathLike[str] | str, dst: os.PathLike[str] | str) -> None:
        dst_path = Path(dst)
        if dst_path.name.endswith(".source.json"):
            raise OSError("boom on sidecar commit")
        real_replace(src, dst)

    monkeypatch.setattr(
        p1_prepare_aozora.urllib.request,
        "build_opener",
        lambda *handlers: _StaticBatchOpener(),
    )
    monkeypatch.setattr(p1_prepare_aozora.os, "replace", _failing_replace)
    with pytest.raises(OSError, match="sidecar commit"):
        p1_prepare_aozora.prepare_aozora_corpora(
            ["https://www.aozora.gr.jp/cards/000148/files/789_ruby_5639.zip"],
            out_dir=tmp_path,
        )
    assert not list(tmp_path.glob("*.txt"))
    assert not list(tmp_path.glob("*.source.json"))
    assert not list(tmp_path.glob("*.tmp"))


def test_prepare_aozora_corpora_reuses_existing_same_url_with_metadata(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    output_path = tmp_path / "aozora_000148_789_ruby_5639.txt"
    text = "既存テキスト\n"
    output_path.write_text(text, encoding="utf-8")
    metadata_path = tmp_path / "aozora_000148_789_ruby_5639.txt.source.json"
    metadata_path.write_text(
        json.dumps(
            {
                "url": "https://www.aozora.gr.jp/cards/000148/files/789_ruby_5639.zip",
                "path": str(output_path.resolve()),
                "chars": len(text),
                "vocab_size": len(set(text)),
                "sha256": p1_prepare_aozora.sha256_text(text),
                "reused_existing": False,
                "metadata_path": str(metadata_path.resolve()),
            },
            ensure_ascii=False,
            indent=2,
        ),
        encoding="utf-8",
    )
    called = False

    class _UnexpectedOpener:
        def open(self, url: str, timeout: float = 30.0) -> _FakeResponse:
            nonlocal called
            called = True
            return _FakeResponse(_aozora_zip_bytes())

    monkeypatch.setattr(
        p1_prepare_aozora.urllib.request,
        "build_opener",
        lambda *handlers: _UnexpectedOpener(),
    )
    records = p1_prepare_aozora.prepare_aozora_corpora(
        ["https://www.aozora.gr.jp/cards/000148/files/789_ruby_5639.zip"],
        out_dir=tmp_path,
    )
    assert called is False
    assert records[0]["reused_existing"] is True
    assert records[0]["chars"] == len(text)


def test_prepare_aozora_corpora_rejects_reuse_when_file_sha256_drifted(tmp_path: Path) -> None:
    output_path = tmp_path / "aozora_000148_789_ruby_5639.txt"
    metadata_path = tmp_path / "aozora_000148_789_ruby_5639.txt.source.json"
    original_text = "元テキスト\n"
    output_path.write_text("改変済み\n", encoding="utf-8")
    metadata_path.write_text(
        json.dumps(
            {
                "url": "https://www.aozora.gr.jp/cards/000148/files/789_ruby_5639.zip",
                "path": str(output_path.resolve()),
                "chars": len(original_text),
                "vocab_size": len(set(original_text)),
                "sha256": p1_prepare_aozora.sha256_text(original_text),
                "reused_existing": False,
                "metadata_path": str(metadata_path.resolve()),
            },
            ensure_ascii=False,
            indent=2,
        ),
        encoding="utf-8",
    )
    with pytest.raises(ValueError, match="metadata sha256"):
        p1_prepare_aozora.prepare_aozora_corpora(
            ["https://www.aozora.gr.jp/cards/000148/files/789_ruby_5639.zip"],
            out_dir=tmp_path,
        )


def test_prepare_aozora_corpora_rejects_existing_mismatched_metadata_url(tmp_path: Path) -> None:
    output_path = tmp_path / "aozora_000148_789_ruby_5639.txt"
    output_path.write_text("old\n", encoding="utf-8")
    metadata_path = tmp_path / "aozora_000148_789_ruby_5639.txt.source.json"
    metadata_path.write_text(
        json.dumps({"url": "https://www.aozora.gr.jp/cards/999999/files/other.zip"}, indent=2),
        encoding="utf-8",
    )
    with pytest.raises(ValueError, match="does not match"):
        p1_prepare_aozora.prepare_aozora_corpora(
            ["https://www.aozora.gr.jp/cards/000148/files/789_ruby_5639.zip"],
            out_dir=tmp_path,
        )


def test_download_aozora_text_rejects_non_aozora_urls() -> None:
    with pytest.raises(ValueError, match="unsupported URL scheme"):
        p1_prepare_aozora._download_aozora_text(  # pyright: ignore[reportPrivateUsage]
            "file:///tmp/aozora.zip",
            timeout=30.0,
        )
    with pytest.raises(ValueError, match="unsupported Aozora host"):
        p1_prepare_aozora._download_aozora_text(  # pyright: ignore[reportPrivateUsage]
            "https://example.com/files/aozora.zip",
            timeout=30.0,
        )


def test_prepare_aozora_corpora_rejects_non_aozora_host_before_any_write(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    called = False

    class _UnexpectedOpener:
        def open(self, url: str, timeout: float = 30.0) -> _FakeResponse:
            nonlocal called
            called = True
            return _FakeResponse(_aozora_zip_bytes())

    monkeypatch.setattr(
        p1_prepare_aozora.urllib.request,
        "build_opener",
        lambda *handlers: _UnexpectedOpener(),
    )
    with pytest.raises(ValueError, match="unsupported Aozora host"):
        p1_prepare_aozora.prepare_aozora_corpora(
            [
                "https://www.aozora.gr.jp/cards/000148/files/789_ruby_5639.zip",
                "https://example.com/files/not-allowed.zip",
            ],
            out_dir=tmp_path,
        )
    assert called is False
    assert not list(tmp_path.glob("*.txt"))


def test_prepare_aozora_corpora_rejects_reuse_with_non_aozora_metadata_url(tmp_path: Path) -> None:
    output_path = tmp_path / "aozora_000148_789_ruby_5639.txt"
    output_path.write_text("old\n", encoding="utf-8")
    metadata_path = tmp_path / "aozora_000148_789_ruby_5639.txt.source.json"
    metadata_path.write_text(
        json.dumps({"url": "https://example.com/files/not-allowed.zip"}, indent=2),
        encoding="utf-8",
    )
    with pytest.raises(ValueError, match="unsupported Aozora host"):
        p1_prepare_aozora.prepare_aozora_corpora(
            ["https://example.com/files/not-allowed.zip"],
            out_dir=tmp_path,
        )


def test_load_existing_metadata_rejects_non_object_json(tmp_path: Path) -> None:
    metadata_path = tmp_path / "bad.source.json"
    metadata_path.write_text('["not", "an", "object"]', encoding="utf-8")
    with pytest.raises(ValueError, match="expected JSON object"):
        p1_prepare_aozora._load_existing_metadata(metadata_path)  # pyright: ignore[reportPrivateUsage]


def test_download_aozora_text_includes_failing_url_in_error(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    bad_payload = b"not-a-zip"

    class _BadPayloadOpener:
        def open(self, url: str, timeout: float = 30.0) -> _FakeResponse:
            return _FakeResponse(bad_payload)

    monkeypatch.setattr(
        p1_prepare_aozora.urllib.request,
        "build_opener",
        lambda *handlers: _BadPayloadOpener(),
    )
    url = "https://www.aozora.gr.jp/cards/000148/files/789_ruby_5639.zip"
    with pytest.raises(ValueError, match=re.escape(url)):
        p1_prepare_aozora._download_aozora_text(  # pyright: ignore[reportPrivateUsage]
            url,
            timeout=30.0,
        )


def test_download_aozora_text_rejects_redirects(monkeypatch: pytest.MonkeyPatch) -> None:
    class _RedirectingOpener:
        def __init__(self, handlers: tuple[object, ...]) -> None:
            self._handlers = handlers

        def open(self, url: str, timeout: float = 30.0) -> _FakeResponse:
            redirect_handler = next(
                handler
                for handler in self._handlers
                if isinstance(handler, p1_prepare_aozora._NoRedirectHandler)
            )
            redirect_handler.redirect_request(
                req=None,
                fp=None,
                code=302,
                msg="Found",
                headers=Message(),
                newurl="https://evil.example.com/redirected.zip",
            )
            raise AssertionError("redirect handler should have raised")

    monkeypatch.setattr(
        p1_prepare_aozora.urllib.request,
        "build_opener",
        lambda *handlers: _RedirectingOpener(handlers),
    )
    with pytest.raises(ValueError, match="redirects are not allowed"):
        p1_prepare_aozora._download_aozora_text(  # pyright: ignore[reportPrivateUsage]
            "https://www.aozora.gr.jp/cards/000148/files/789_ruby_5639.zip",
            timeout=30.0,
        )


def test_script_entrypoint_runs_via_subprocess(tmp_path: Path) -> None:
    payload_file = tmp_path / "payload.zip"
    payload_file.write_bytes(_aozora_zip_bytes())
    bootstrap = (
        "import os, runpy, urllib.request\n"
        "from pathlib import Path\n"
        "payload = Path(os.environ['AOZORA_TEST_PAYLOAD']).read_bytes()\n"
        "class Resp:\n"
        "    def __init__(self, data): self._data = data\n"
        "    def read(self): return self._data\n"
        "    def __enter__(self): return self\n"
        "    def __exit__(self, exc_type, exc, tb): return None\n"
        "class Opener:\n"
        "    def open(self, url, timeout=30.0): return Resp(payload)\n"
        "urllib.request.build_opener = lambda *handlers: Opener()\n"
        "runpy.run_path('scripts/p1_prepare_aozora.py', run_name='__main__')\n"
    )
    out_dir = tmp_path / "prepared"
    proc = subprocess.run(
        [
            sys.executable,
            "-c",
            bootstrap,
            "--out-dir",
            str(out_dir),
            "https://www.aozora.gr.jp/cards/000148/files/789_ruby_5639.zip",
        ],
        cwd=Path(__file__).resolve().parents[2],
        env={**os.environ, "AOZORA_TEST_PAYLOAD": str(payload_file)},
        capture_output=True,
        text=True,
        check=False,
    )
    assert proc.returncode == 0, proc.stderr
    assert (out_dir / "aozora_000148_789_ruby_5639.txt").exists()
